#!/bin/bash
# 颜色定义管理

# 基础颜色
export COLOR_RESET="\033[0m"
export COLOR_BLACK="\033[30m"
export COLOR_RED="\033[31m"
export COLOR_GREEN="\033[32m"
export COLOR_YELLOW="\033[33m"
export COLOR_BLUE="\033[34m"
export COLOR_PURPLE="\033[35m"
export COLOR_CYAN="\033[36m"
export COLOR_WHITE="\033[37m"

# 高亮颜色
export COLOR_BRIGHT_BLACK="\033[1;30m"
export COLOR_BRIGHT_RED="\033[1;31m"
export COLOR_BRIGHT_GREEN="\033[1;32m"
export COLOR_BRIGHT_YELLOW="\033[1;33m"
export COLOR_BRIGHT_BLUE="\033[1;34m"
export COLOR_BRIGHT_PURPLE="\033[1;35m"
export COLOR_BRIGHT_CYAN="\033[1;36m"
export COLOR_BRIGHT_WHITE="\033[1;37m"

# 背景颜色
export COLOR_BG_BLACK="\033[40m"
export COLOR_BG_RED="\033[41m"
export COLOR_BG_GREEN="\033[42m"
export COLOR_BG_YELLOW="\033[43m"
export COLOR_BG_BLUE="\033[44m"
export COLOR_BG_PURPLE="\033[45m"
export COLOR_BG_CYAN="\033[46m"
export COLOR_BG_WHITE="\033[47m"

# 特殊格式
export COLOR_BOLD="\033[1m"
export COLOR_DIM="\033[2m"
export COLOR_UNDERLINE="\033[4m"
export COLOR_BLINK="\033[5m"
export COLOR_REVERSE="\033[7m"
export COLOR_HIDDEN="\033[8m"

# UI主题颜色
export COLOR_HEADER="${COLOR_CYAN}"
export COLOR_TITLE="${COLOR_BRIGHT_BLUE}"
export COLOR_INFO="${COLOR_GREEN}"
export COLOR_WARNING="${COLOR_YELLOW}"
export COLOR_ERROR="${COLOR_RED}"
export COLOR_DEBUG="${COLOR_PURPLE}"
export COLOR_PROMPT="${COLOR_BRIGHT_GREEN}"
export COLOR_SUCCESS="${COLOR_BRIGHT_GREEN}"
export COLOR_FAILURE="${COLOR_BRIGHT_RED}"

# 菜单颜色
export COLOR_MENU_BORDER="${COLOR_CYAN}"
export COLOR_MENU_TITLE="${COLOR_BRIGHT_BLUE}"
export COLOR_MENU_ITEM="${COLOR_GREEN}"
export COLOR_MENU_SELECTED="${COLOR_BRIGHT_GREEN}"
export COLOR_MENU_DISABLED="${COLOR_DIM}"

# 状态颜色
export COLOR_STATUS_OK="${COLOR_GREEN}"
export COLOR_STATUS_WARN="${COLOR_YELLOW}"
export COLOR_STATUS_ERROR="${COLOR_RED}"
export COLOR_STATUS_UNKNOWN="${COLOR_GRAY}"
